// <auto-generated />
namespace LeonVanDyk.WMTestApp.SchoolContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ValidationChecks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ValidationChecks));
        
        string IMigrationMetadata.Id
        {
            get { return "201806211248384_ValidationChecks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
